version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
  - master
skip_tags: true
environment:
  PATH: 'C:\Ruby200\bin;%PATH%'
init:
- cmd: gem install bundler
install:
- cmd: bundle install
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: artifacts\**\*.*
deploy: off
