version: '{build}'
image:
- Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
  - master
build_script:
- cmd: ./build.cmd
test: off
artifacts:
- path: artifacts\**\*.*
deploy: off
