version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
  - master
environment:
  BUILD_NUMBER: $(APPVEYOR_BUILD_NUMBER)
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: artifacts\**\*.*
deploy: off
